### PR TITLE
Add unsafeRandom function

### PR DESCRIPTION
**Pull request by Trottoir**
`unsafeRandom` generates now a random Number between 0 and the max Safe integer

### CODE REVIEW

**Review by Thykof — COMMENTED** [review]
could you provide a unit test sample that show case the random function please, to test if it works

**Comment by ASAPSegfault** [comment]
When setStorage is called an event with a random number is fired so I can confirm it works.
Although having a separate function is cool I'm not sure it's necesserary WDYT @Trottoir ?

**Review by SebastienValla — APPROVED** [review]

**Comment by Trottoir** [comment]
@Thykof 
I don't see what kind of unit test I can provide for a random number generation
AS @ASAPSegfault I'm already fireing a call to the `usageRandom` function that showcase the usage of the function :)

**Comment by Thykof** [comment]
@Trottoir yeah but I don't know how to trigger from test panel

**Comment by Trottoir** [comment]
> @Trottoir yeah but I don't know how to trigger from test panel

When you hit `Test` button, an event is generated and it prints you the random number generated
Maybe try to clean your storage as the previous example may be still stored

**Pull request merged**
